import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Hoodie Oversize "NOIZE"',
    description: 'Hoodie oversize algodón premium 380gsm. Estampado gráfico en espalda.',
    price: 45000,
    originalPrice: 52000,
    images: ['/products/hoodie-noize.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'hoodies',
    stock: 15,
    featured: true,
    slug: 'hoodie-oversize-noize',
  },
  {
    id: '2',
    name: 'Cargo Pants "SHADOW"',
    description: 'Pantalón cargo wide-leg con bolsillos utility. Tela ripstop.',
    price: 38000,
    images: ['/products/cargo-shadow.jpg'],
    sizes: ['28', '30', '32', '34', '36'],
    category: 'bottoms',
    stock: 20,
    featured: true,
    slug: 'cargo-pants-shadow',
  },
  {
    id: '3',
    name: 'Remera Boxy "STATIC"',
    description: 'Remera boxy fit 240gsm. Print serigráfico de alta definición.',
    price: 22000,
    images: ['/products/tee-static.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'tees',
    stock: 30,
    featured: true,
    slug: 'remera-boxy-static',
  },
  {
    id: '4',
    name: 'Jacket Windbreaker "DRIFT"',
    description: 'Rompevientos liviano con capucha. Reflectivo en mangas.',
    price: 55000,
    originalPrice: 62000,
    images: ['/products/jacket-drift.jpg'],
    sizes: ['M', 'L', 'XL'],
    category: 'outerwear',
    stock: 8,
    featured: true,
    slug: 'jacket-windbreaker-drift',
  },
  {
    id: '5',
    name: 'Shorts Mesh "COURT"',
    description: 'Shorts de mesh doble capa. Cintura elástica con cordón.',
    price: 18000,
    images: ['/products/shorts-court.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'bottoms',
    stock: 25,
    featured: false,
    slug: 'shorts-mesh-court',
  },
  {
    id: '6',
    name: 'Beanie "FROST"',
    description: 'Gorro de lana con parche bordado KAKO.',
    price: 12000,
    images: ['/products/beanie-frost.jpg'],
    sizes: ['Único'],
    category: 'accessories',
    stock: 40,
    featured: false,
    slug: 'beanie-frost',
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos' },
  { id: 'hoodies', name: 'Hoodies' },
  { id: 'tees', name: 'Remeras' },
  { id: 'bottoms', name: 'Bottoms' },
  { id: 'outerwear', name: 'Outerwear' },
  { id: 'accessories', name: 'Accesorios' },
];
