import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Hoodie Supreme Box Logo SS24',
    description: 'Hoodie Supreme Box Logo temporada SS24. Color gris claro, calidad premium.',
    price: 128000,
    originalPrice: 143000,
    cost: 64800,
    images: ['/products/SupremeBuzorgris.jpeg'],
    sizes: ['M', 'L', 'XL'],
    category: 'hoodies',
    stock: 5,
    featured: true,
    slug: 'hoodie-supreme-box-logo-ss24',
    weight: 910,
  },
  {
    id: '2',
    name: 'Hoodie Essentials Oversize',
    description: 'Hoodie Essentials con letras 3D estilo europeo/americano. Interior con felpa, corte oversize. Color negro.',
    price: 75000,
    cost: 37400,
    images: ['/products/BuzoEssentialsnegro.jpeg'],
    sizes: ['M', 'L', 'XL'],
    category: 'hoodies',
    stock: 8,
    featured: true,
    slug: 'hoodie-essentials-oversize',
    weight: 650,
  },
  {
    id: '3',
    name: 'Hoodie Spider Brillante',
    description: 'Hoodie pesado 450GSM con estampado Spider en relieve con brillo. Felpa gruesa, ideal para invierno.',
    price: 123000,
    originalPrice: 138000,
    cost: 61900,
    images: ['/products/BuzoSpiderBrillos.jpeg'],
    sizes: ['M', 'L', 'XL'],
    category: 'hoodies',
    stock: 6,
    featured: true,
    slug: 'hoodie-spider-450gsm',
    weight: 860,
  },
  {
    id: '4',
    name: 'Jean Streetwear Wide-Leg',
    description: 'Jean estilo streetwear, corte wide-leg. Tela resistente, color negro.',
    price: 102000,
    cost: 59600,
    images: ['/products/JeanValley.jpeg'],
    sizes: ['M', 'L', 'XL'],
    category: 'bottoms',
    stock: 10,
    featured: true,
    slug: 'jean-streetwear-wide-leg',
    weight: 950,
  },
  {
    id: '5',
    name: 'Remera Mixed Emotions',
    description: 'Remera con estampado completo estilo angel vintage con logo de strass/brillantes. Oversize, hip-hop. Color negro.',
    price: 62000,
    cost: 31200,
    images: ['/products/RemeraMixedEmmotions.jpeg'],
    sizes: ['M', 'L', 'XL'],
    category: 'tees',
    stock: 12,
    featured: true,
    slug: 'remera-mixed-emotions',
    weight: 500,
  },
  {
    id: '6',
    name: 'Gorra Amiri Bordada - Negra',
    description: 'Gorra Amiri con logo bordado, version correcta. Ajustable. Color negro.',
    price: 46000,
    cost: 23100,
    images: ['/products/GorraNegraAmiri.jpeg'],
    sizes: ['Unico'],
    category: 'accessories',
    stock: 15,
    featured: false,
    slug: 'gorra-amiri-negra',
    weight: 200,
  },
  {
    id: '7',
    name: 'Gorra Amiri Bordada - Negra 2',
    description: 'Gorra Amiri con logo bordado, version correcta. Ajustable. Color negro.',
    price: 46000,
    cost: 23100,
    images: ['/products/GorraNegraAmiri.jpeg'],
    sizes: ['Unico'],
    category: 'accessories',
    stock: 15,
    featured: false,
    slug: 'gorra-amiri-negra-2',
    weight: 200,
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos' },
  { id: 'hoodies', name: 'Hoodies' },
  { id: 'tees', name: 'Remeras' },
  { id: 'bottoms', name: 'Jeans' },
  { id: 'accessories', name: 'Accesorios' },
];
