import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Hoodie Supreme Box Logo SS24',
    description: 'Hoodie Supreme Box Logo temporada SS24. Color gris claro, calidad premium. Talle L.',
    price: 45000,
    originalPrice: 52000,
    images: ['/products/hoodie-supreme.jpg'],
    sizes: ['M', 'L', 'XL'],
    category: 'hoodies',
    stock: 5,
    featured: true,
    slug: 'hoodie-supreme-box-logo-ss24',
    weight: 910,
  },
  {
    id: '2',
    name: 'Hoodie Essentials Oversize',
    description: 'Hoodie Essentials con letras 3D estilo europeo/americano. Interior con felpa, corte oversize. Color negro.',
    price: 28000,
    images: ['/products/hoodie-essentials.jpg'],
    sizes: ['M', 'L', 'XL'],
    category: 'hoodies',
    stock: 8,
    featured: true,
    slug: 'hoodie-essentials-oversize',
    weight: 650,
  },
  {
    id: '3',
    name: 'Hoodie Spider Brillante 450GSM',
    description: 'Hoodie pesado 450GSM con estampado Spider en relieve con brillo. Felpa gruesa, ideal para invierno.',
    price: 42000,
    originalPrice: 48000,
    images: ['/products/hoodie-spider.jpg'],
    sizes: ['M', 'L', 'XL'],
    category: 'hoodies',
    stock: 6,
    featured: true,
    slug: 'hoodie-spider-450gsm',
    weight: 860,
  },
  {
    id: '4',
    name: 'Pantalón Cargo Streetwear',
    description: 'Pantalón cargo estilo streetwear, corte wide-leg. Tela resistente, bolsillos utility. Color negro.',
    price: 38000,
    images: ['/products/cargo-pants.jpg'],
    sizes: ['M', 'L', 'XL'],
    category: 'bottoms',
    stock: 10,
    featured: true,
    slug: 'pantalon-cargo-streetwear',
    weight: 950,
  },
  {
    id: '5',
    name: 'Remera Mixed Emotions',
    description: 'Remera con estampado completo estilo ángel vintage con logo de strass/brillantes. Oversize, hip-hop. Color negro.',
    price: 22000,
    images: ['/products/tee-mixed-emotions.jpg'],
    sizes: ['M', 'L', 'XL'],
    category: 'tees',
    stock: 12,
    featured: true,
    slug: 'remera-mixed-emotions',
    weight: 500,
  },
  {
    id: '6',
    name: 'Gorra Amiri Bordada - Negra',
    description: 'Gorra Amiri con logo bordado, versión correcta. Ajustable. Color negro.',
    price: 18000,
    images: ['/products/cap-amiri-black.jpg'],
    sizes: ['Único'],
    category: 'accessories',
    stock: 15,
    featured: false,
    slug: 'gorra-amiri-negra',
    weight: 200,
  },
  {
    id: '7',
    name: 'Gorra Amiri Bordada - Marrón',
    description: 'Gorra Amiri con logo bordado, versión correcta. Ajustable. Color marrón.',
    price: 18000,
    images: ['/products/cap-amiri-brown.jpg'],
    sizes: ['Único'],
    category: 'accessories',
    stock: 15,
    featured: false,
    slug: 'gorra-amiri-marron',
    weight: 200,
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos' },
  { id: 'hoodies', name: 'Hoodies' },
  { id: 'tees', name: 'Remeras' },
  { id: 'bottoms', name: 'Pantalones' },
  { id: 'accessories', name: 'Accesorios' },
];
